package com.skeletonarmy.marrow.prompts;

public enum Button {
    A, B, X, Y,
    DPAD_UP, DPAD_DOWN, DPAD_LEFT, DPAD_RIGHT,
    GUIDE, START, BACK,
    LEFT_BUMPER, RIGHT_BUMPER,
    LEFT_STICK_BUTTON, RIGHT_STICK_BUTTON,
    CIRCLE, CROSS, TRIANGLE, SQUARE,
    SHARE, OPTIONS, TOUCHPAD,
    TOUCHPAD_FINGER_1, TOUCHPAD_FINGER_2,
    PS
}
