name: Trigger JitPack Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  trigger-jitpack:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger JitPack build for pushed branch
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Triggering JitPack build for branch: $BRANCH_NAME"
          curl -X GET "https://jitpack.io/api/builds/com.github.Skeleton-Army/Marrow/${BRANCH_NAME}"
          curl -X GET "https://jitpack.io/com/github/Skeleton-Army/Marrow/${BRANCH_NAME}-SNAPSHOT/build.log"
