name: Update README Marrow Version

on:
  push:
    tags:
      - 'v*'  # Run when a new version tag is pushed (like v1.0.0)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: get_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Replace version in README
        run: |
          sed -i "s|implementation 'com.github.Skeleton-Army:Marrow:.*'|implementation 'com.github.Skeleton-Army:Marrow:${TAG_NAME}'|g" README.md

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update Marrow version to ${TAG_NAME} in README"
          git push
